# Generated by Django 5.2.8 on 2025-11-30 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='author',
            new_name='user',
        ),
    ]
